/**
 * 카드를 GitHub에 바로 커밋 가능한 포맷으로 내보낸다.
 *
 *   1) toStandaloneHtml — 스타일·폰트 인라인된 단독 HTML. 그대로 /cards/foo.html
 *      로 커밋하면 GitHub Pages에서 렌더됨.
 *   2) toMarkdown       — GitHub Flavored Markdown. README나 /docs/*.md에 붙여넣기.
 */

import type { EditorialCardData } from "./types";

// ---------------------------------------------------------------------------
// 안전한 HTML escape
// ---------------------------------------------------------------------------

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// ---------------------------------------------------------------------------
// 안전한 파일명 생성
// ---------------------------------------------------------------------------

export function suggestFilename(card: EditorialCardData, ext: "html" | "md"): string {
  const base = (card.headline || "folio-card")
    .toLowerCase()
    .replace(/[^a-z0-9가-힣]+/gi, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);
  const date = card.fetchedAt.slice(0, 10);
  return `${date}-${base || "card"}.${ext}`;
}

// ---------------------------------------------------------------------------
// Markdown 내보내기
// ---------------------------------------------------------------------------

export function toMarkdown(card: EditorialCardData): string {
  const lines: string[] = [];
  const date = card.fetchedAt.slice(0, 10);

  // YAML frontmatter (Jekyll/Hugo/Astro 호환)
  lines.push("---");
  lines.push(`title: "${card.headline.replace(/"/g, '\\"')}"`);
  lines.push(`description: "${card.dek.replace(/"/g, '\\"').slice(0, 200)}"`);
  lines.push(`date: ${date}`);
  lines.push(`source: ${card.sourceUrl}`);
  if (card.sourceSiteName) lines.push(`site: "${card.sourceSiteName}"`);
  lines.push(`category: "${card.eyebrow}"`);
  if (card.heroImage) lines.push(`image: ${card.heroImage}`);
  lines.push("---");
  lines.push("");

  // 카테고리 · 키커
  lines.push(`**${card.eyebrow}**${card.kicker ? ` · ${card.kicker}` : ""}`);
  lines.push("");

  // 헤드라인
  lines.push(`# ${card.headline}`);
  lines.push("");

  // 데크
  if (card.dek) {
    lines.push(`> *${card.dek}*`);
    lines.push("");
  }

  // 히어로 이미지
  if (card.heroImage) {
    lines.push(`![${esc(card.headline)}](${card.heroImage})`);
    lines.push("");
  }

  // By line
  lines.push(`— **${card.sourceSiteName ?? card.sourceDomain}**`);
  lines.push("");
  lines.push("---");
  lines.push("");

  // 리드
  lines.push(card.lead);
  lines.push("");

  // 본문
  for (const p of card.bodyParagraphs) {
    lines.push(p);
    lines.push("");
  }

  // 풀쿼트
  if (card.pullQuote) {
    lines.push(`> ## "${card.pullQuote}"`);
    lines.push(`> — ${card.sourceSiteName ?? card.sourceDomain}`);
    lines.push("");
  }

  // 핵심 포인트
  if (card.keyPoints.length > 0) {
    const isKo = card.lang === "ko" || card.lang === "mixed";
    lines.push(`### ${isKo ? "핵심 메모" : "Field Notes"}`);
    lines.push("");
    card.keyPoints.forEach((k, i) => {
      lines.push(`${i + 1}. ${k}`);
    });
    lines.push("");
  }

  // Footer
  lines.push("---");
  lines.push("");
  lines.push(`↳ Source: [${card.sourceDomain}](${card.sourceUrl})`);
  lines.push(`· Composed: ${date}`);
  lines.push("· _Generated by [Folio Cards](https://github.com/seong-ro/nest-alum1) — deterministic editorial card compositor._");
  lines.push("");

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// 단독 HTML 내보내기 (폰트·스타일 인라인)
// ---------------------------------------------------------------------------

export function toStandaloneHtml(card: EditorialCardData): string {
  const isKo = card.lang === "ko" || card.lang === "mixed";
  const paletteVars =
    card.palette === "ink"
      ? "--card-bg:#1b1a17;--card-bg-soft:#2b2925;--card-ink:#f2ede1;--card-accent:#d9a066;"
      : card.palette === "clay"
      ? "--card-bg:#eadccb;--card-bg-soft:#ded0b9;--card-ink:#2a1a10;--card-accent:#7a2f17;"
      : "--card-bg:#f2ede1;--card-bg-soft:#ebe4d2;--card-ink:#1b1a17;--card-accent:#a64b2a;";

  const headBlocks: string[] = [];
  if (card.bodyParagraphs.length > 0) {
    headBlocks.push(
      ...card.bodyParagraphs
        .slice(0, 2)
        .map((p) => `<p class="body">${esc(p)}</p>`),
    );
  }

  const sideBlocks: string[] = [];
  if (card.pullQuote) {
    sideBlocks.push(`
      <blockquote class="pull">
        <span class="qm" aria-hidden="true">&ldquo;</span>
        <p>${esc(card.pullQuote)}</p>
        <footer>— ${esc(card.sourceSiteName ?? card.sourceDomain)}</footer>
      </blockquote>`);
  }
  if (card.keyPoints.length > 0) {
    const items = card.keyPoints
      .map(
        (k, i) =>
          `<li><span class="n">${String(i + 1).padStart(2, "0")}</span><span>${esc(
            k,
          )}</span></li>`,
      )
      .join("");
    sideBlocks.push(`
      <section class="keypoints">
        <div class="kp-head">
          <span class="dash"></span>
          <span class="eyebrow accent">${isKo ? "핵심 메모" : "Field Notes"}</span>
        </div>
        <ol>${items}</ol>
      </section>`);
  }

  const tail =
    card.bodyParagraphs.length > 2
      ? `<div class="tail">${card.bodyParagraphs
          .slice(2)
          .map((p) => `<p class="body small">${esc(p)}</p>`)
          .join("")}</div>`
      : "";

  const hero = card.heroImage
    ? `<figure class="hero"><img src="${esc(card.heroImage)}" alt="" onerror="this.parentElement.remove()"/><figcaption>▲ ${esc(
        card.sourceDomain,
      )}</figcaption></figure>`
    : "";

  const lang = isKo ? "ko" : "en";

  return `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(card.headline)}</title>
<meta name="description" content="${esc(card.dek).slice(0, 200)}">
<meta property="og:title" content="${esc(card.headline)}">
<meta property="og:description" content="${esc(card.dek).slice(0, 200)}">
${card.heroImage ? `<meta property="og:image" content="${esc(card.heroImage)}">` : ""}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght,SOFT,WONK@0,9..144,300..900,0..100,0..1&family=Newsreader:ital,opsz,wght@0,6..72,300..700;1,6..72,300..700&family=Noto+Serif+KR:wght@300;400;500;700;900&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/variable/pretendardvariable.css" rel="stylesheet">
<style>
:root { ${paletteVars} }
* { box-sizing: border-box; margin: 0; padding: 0; }
html, body { background: #e8e2d4; color: var(--card-ink); font-family: "Pretendard Variable", "Pretendard", sans-serif; -webkit-font-smoothing: antialiased; }
body { padding: 40px 16px 60px; min-height: 100vh; }
.card { max-width: 960px; margin: 0 auto; background: var(--card-bg); color: var(--card-ink); box-shadow: 0 30px 80px -40px rgba(0,0,0,0.35), 0 1px 0 0 rgba(27,26,23,0.25); padding: 32px 40px 48px; background-image: radial-gradient(rgba(27,26,23,0.035) 1px, transparent 1px), radial-gradient(rgba(27,26,23,0.025) 1px, transparent 1px); background-size: 3px 3px, 7px 7px; background-position: 0 0, 1px 2px; }
.runhead { display: flex; justify-content: space-between; font-size: 11px; letter-spacing: 0.22em; text-transform: uppercase; opacity: 0.78; padding-bottom: 12px; }
.rule-double { border-top: 1px solid var(--card-ink); border-bottom: 1px solid var(--card-ink); height: 5px; margin-bottom: 36px; opacity: 0.85; }
.eyebrow-row { display: flex; align-items: center; gap: 16px; color: var(--card-accent); margin-bottom: 20px; }
.eyebrow { font-weight: 600; letter-spacing: 0.22em; text-transform: uppercase; font-size: 12px; }
.eyebrow-ko { font-weight: 600; letter-spacing: 0.3em; font-size: 12px; }
.dash-h { width: 28px; height: 1px; background: var(--card-accent); }
.accent { color: var(--card-accent); }
h1 { font-family: "Fraunces", "Noto Serif KR", serif; font-weight: 450; font-size: clamp(2.2rem, 5.6vw, 4.4rem); line-height: 0.98; letter-spacing: -0.01em; margin-bottom: 22px; font-variation-settings: "opsz" 144, "SOFT" 30, "WONK" 1; }
.dek { font-family: "Newsreader", "Noto Serif KR", serif; font-style: italic; font-size: clamp(1.05rem, 1.8vw, 1.3rem); line-height: 1.45; opacity: 0.88; max-width: 48rem; margin-bottom: 30px; }
.byline { display: flex; align-items: center; gap: 16px; margin-bottom: 36px; }
.byline-rule { flex: 1; height: 1px; background: var(--card-ink); opacity: 0.25; }
.byline-text { font-size: 11px; letter-spacing: 0.22em; text-transform: uppercase; opacity: 0.72; }
.byline-text b { color: var(--card-accent); font-weight: 600; }
.hero { margin-bottom: 36px; }
.hero img { width: 100%; aspect-ratio: 16/9; object-fit: cover; border: 1px solid var(--card-ink); filter: saturate(0.88) contrast(1.02); display: block; }
.hero figcaption { margin-top: 8px; font-size: 10.5px; letter-spacing: 0.2em; text-transform: uppercase; opacity: 0.55; }
.grid { display: grid; grid-template-columns: 1fr; gap: 28px; }
@media (min-width: 720px) { .grid { grid-template-columns: 7fr 5fr; gap: 40px; } }
.body { font-family: "Newsreader", "Noto Serif KR", serif; font-size: 17px; line-height: 1.7; text-align: justify; hyphens: auto; }
.body + .body { margin-top: 18px; }
.body.small { font-size: 16px; line-height: 1.65; }
.body:first-child::first-letter { font-family: "Fraunces", serif; font-weight: 500; font-size: 5.2rem; line-height: 0.88; float: left; padding: 3px 10px 0 0; color: var(--card-accent); }
.pull { border-top: 2px solid var(--card-ink); border-bottom: 2px solid var(--card-ink); padding: 22px 0 18px; position: relative; }
.qm { font-family: "Fraunces", serif; font-weight: 300; font-size: 5rem; line-height: 0.5; color: var(--card-accent); display: inline-block; vertical-align: -0.3em; margin-right: 4px; }
.pull p { font-family: "Fraunces", "Noto Serif KR", serif; font-weight: 430; font-size: 1.35rem; line-height: 1.32; letter-spacing: -0.005em; display: inline; font-variation-settings: "opsz" 36, "SOFT" 50; }
.pull footer { display: block; margin-top: 14px; font-size: 10.5px; letter-spacing: 0.22em; text-transform: uppercase; opacity: 0.7; }
.keypoints { margin-top: 0; }
.kp-head { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }
.kp-head .dash { width: 32px; height: 1px; background: var(--card-accent); display: inline-block; }
.keypoints ol { list-style: none; display: flex; flex-direction: column; gap: 14px; }
.keypoints li { display: flex; gap: 16px; align-items: baseline; }
.keypoints .n { font-family: "Fraunces", serif; font-size: 1.6rem; line-height: 1; color: var(--card-accent); flex-shrink: 0; min-width: 42px; font-feature-settings: "onum"; font-variation-settings: "opsz" 48; }
.keypoints li span:last-child { font-family: "Newsreader", "Noto Serif KR", serif; font-size: 0.98rem; line-height: 1.55; }
.tail { grid-column: 1 / -1; display: grid; grid-template-columns: 1fr; gap: 16px 40px; margin-top: 32px; }
@media (min-width: 720px) { .tail { grid-template-columns: 1fr 1fr; } }
.foot-rule { height: 1px; background: var(--card-ink); opacity: 0.85; margin-top: 48px; }
.foot-meta { display: flex; flex-wrap: wrap; justify-content: space-between; gap: 12px; padding-top: 14px; font-size: 11px; letter-spacing: 0.2em; text-transform: uppercase; opacity: 0.75; }
.foot-url { font-family: "JetBrains Mono", monospace; text-transform: none; letter-spacing: 0; opacity: 0.82; }
</style>
</head>
<body>
<article class="card">
  <header class="runhead">
    <span>N° ${esc(deriveIssue(card.fetchedAt))} · ${esc(formatDate(card.fetchedAt, isKo))}</span>
    <span>Folio / Editorial</span>
  </header>

  <div class="rule-double"></div>

  <div class="eyebrow-row">
    <span class="${/[가-힣]/.test(card.eyebrow) ? "eyebrow-ko" : "eyebrow"}">${esc(card.eyebrow)}</span>
    ${card.kicker ? `<span class="dash-h"></span><span class="eyebrow accent">${esc(card.kicker)}</span>` : ""}
  </div>

  <h1>${esc(card.headline)}</h1>
  ${card.dek && card.dek !== card.headline ? `<p class="dek">${esc(card.dek)}</p>` : ""}

  <div class="byline">
    <span class="byline-rule"></span>
    <span class="byline-text">By <b>${esc(card.sourceSiteName ?? card.sourceDomain)}</b></span>
    <span class="byline-rule"></span>
  </div>

  ${hero}

  <div class="grid">
    <div class="lead-col">
      <p class="body">${esc(card.lead)}</p>
      ${headBlocks.join("\n      ")}
    </div>
    <aside class="side-col">
      ${sideBlocks.join("\n      ")}
    </aside>
  </div>

  ${tail}

  <div class="foot-rule"></div>
  <div class="foot-meta">
    <span>↳ ${esc(card.sourceDomain)}</span>
    <span class="foot-url">${esc(card.sourceUrl)}</span>
    <span>${isKo ? "Folio 에디토리얼" : "A Folio Composition"}</span>
  </div>
</article>
</body>
</html>`;
}

function deriveIssue(iso: string): string {
  const d = new Date(iso);
  const dayOfYear = Math.floor(
    (d.getTime() - new Date(d.getFullYear(), 0, 0).getTime()) /
      (1000 * 60 * 60 * 24),
  );
  return `${String(d.getFullYear()).slice(2)}·${String(dayOfYear).padStart(3, "0")}`;
}

function formatDate(iso: string, ko: boolean): string {
  const d = new Date(iso);
  if (ko) return `${d.getFullYear()}년 ${d.getMonth() + 1}월 ${d.getDate()}일`;
  return d.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

// ---------------------------------------------------------------------------
// 편의 alias + 브라우저 사이드 헬퍼 (CardDetail용)
// ---------------------------------------------------------------------------

/** toStandaloneHtml의 별칭 */
export function toHtml(card: EditorialCardData): string {
  return toStandaloneHtml(card);
}

/** 파일명 생성 간편 API (확장자 추론) */
export function suggestFilenameSimple(card: EditorialCardData): string {
  return suggestFilename(card, "html").replace(/\.html$/, "");
}

/** 브라우저에서 Blob 다운로드 */
export function downloadFile(
  filename: string,
  content: string,
  mimeType: string = "text/plain",
): void {
  if (typeof window === "undefined") return;
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.style.display = "none";
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/** 클립보드 복사 */
export async function copyToClipboard(text: string): Promise<boolean> {
  if (typeof window === "undefined" || typeof navigator === "undefined") return false;
  try {
    if (navigator.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    // 폴백
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.focus();
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}
